[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npm install --include=dev"]

[phases.build]
cmds = ["npm run build"]
[phases.build.environment]
NODE_ENV = "production"

[start]
cmd = "npm start"
